import type { WorkspaceMockData } from "./types";

export const dispatchWorkspaceMock: WorkspaceMockData = {
  object: {
    id: "asia-park",
    name: "Asia Park Astana",
    shortName: "Asia Park",
    address: "Астана, Казахстан",
    kind: "Торгово-развлекательный объект",
    status: "warning",
    mode: "auto",
    updatedAt: "22.05.2026 01:56 Asia/Qyzylorda",
  },
  floors: [
    {
      id: "floor-11400",
      objectId: "asia-park",
      name: "Техническая отметка +11.400",
      level: "+11.400",
      summary: "Кинотеатр, вентиляционные камеры, холодоснабжение",
    },
    {
      id: "floor-12600",
      objectId: "asia-park",
      name: "Техническая отметка +12.600",
      level: "+12.600",
      summary: "Венткамера VC-13-03, насосные группы, сервисные зоны",
    },
    {
      id: "floor-13500",
      objectId: "asia-park",
      name: "Техническая отметка +13.500",
      level: "+13.500",
      summary: "Венткамеры VC-13, кровля, холодоснабжение",
    },
  ],
  zones: [
    {
      id: "zone-cinema",
      floorId: "floor-11400",
      name: "Кинотеатр / проекционная",
      kind: "cinema",
      status: "normal",
      temperature: "21.8 °C",
      humidity: "42%",
      co2: "665 ppm",
      bounds: { x: 7, y: 10, width: 37, height: 34 },
    },
    {
      id: "zone-chw-plant",
      floorId: "floor-11400",
      name: "Холодильный центр",
      kind: "plant",
      status: "warning",
      temperature: "18.6 °C",
      humidity: "39%",
      co2: "510 ppm",
      bounds: { x: 48, y: 9, width: 44, height: 36 },
    },
    {
      id: "zone-retail-a",
      floorId: "floor-12600",
      name: "Торговая зона A",
      kind: "retail",
      status: "warning",
      temperature: "23.1 °C",
      humidity: "45%",
      co2: "740 ppm",
      bounds: { x: 8, y: 48, width: 38, height: 41 },
    },
    {
      id: "zone-service",
      floorId: "floor-12600",
      name: "Сервисная зона / ШУ",
      kind: "service",
      status: "critical",
      temperature: "20.3 °C",
      humidity: "38%",
      co2: "590 ppm",
      bounds: { x: 50, y: 49, width: 41, height: 40 },
    },
    {
      id: "zone-roof",
      floorId: "floor-13500",
      name: "Кровля / градирня",
      kind: "plant",
      status: "normal",
      temperature: "16.2 °C",
      humidity: "36%",
      co2: "480 ppm",
      bounds: { x: 8, y: 10, width: 39, height: 35 },
    },
    {
      id: "zone-ahu",
      floorId: "floor-13500",
      name: "Венткамеры VC-13",
      kind: "plant",
      status: "warning",
      temperature: "19.4 °C",
      humidity: "41%",
      co2: "612 ppm",
      bounds: { x: 52, y: 10, width: 39, height: 35 },
    },
  ],
  systems: [
    {
      id: "hvac",
      name: "HVAC общий контур",
      shortName: "HVAC",
      layer: "hvac",
      status: "warning",
      description: "Общий эксплуатационный контур: зоны, оборудование, аварии и BMS/SCADA.",
    },
    {
      id: "cooling",
      name: "Холодоснабжение",
      shortName: "Cooling",
      layer: "cooling",
      status: "critical",
      description: "Чиллеры Trane, насосные группы, контуры гликоль/вода/фанкойлы.",
    },
    {
      id: "ventilation",
      name: "Вентиляция",
      shortName: "Ventilation",
      layer: "ventilation",
      status: "warning",
      description: "AHU VC-13/VC-11, вентиляционные камеры, заслонки и фильтры.",
    },
    {
      id: "conditioning",
      name: "Кондиционирование / фанкойлы",
      shortName: "Fan coils",
      layer: "hvac",
      status: "warning",
      description: "Фанкойлы, клапаны, торговые зоны и комнатные параметры.",
    },
    {
      id: "heating",
      name: "Отопление / ИТП",
      shortName: "Heating",
      layer: "hvac",
      status: "normal",
      description: "ИТП, теплообменные узлы, подача/обратка и клапаны.",
    },
  ],
  equipment: [
    {
      id: "ch-001",
      name: "Чиллер CH-1",
      displayName: "Чиллер CH-1",
      sourceAlias: "SCADA.CHW.CHILLER.CH1",
      type: "chiller",
      systemId: "cooling",
      floorId: "floor-11400",
      zoneId: "zone-chw-plant",
      status: "warning",
      mode: "auto",
      updatedAt: "12 sec ago",
      position: { x: 74, y: 25 },
      model3d: {
        kind: "chiller",
        twinId: "chiller",
        src: "/models/dispatch/chiller.glb",
        nodeId: "chiller-ch1",
        position: { x: 74, y: 25, z: 1 },
        scale: 1,
      },
      telemetry: {
        "Supply water temp": "6.3 °C",
        "Return water temp": "11.7 °C",
        "Compressor status": "RUN",
        "Pump status": "RUN",
        Pressure: "2.2 bar",
        "Power consumption": "412 kW",
        COP: "4.18",
      },
      capabilities: {
        canRead: true,
        canWrite: false,
        hasAlarms: true,
        hasTrends: true,
        supportsAck: false,
        supportsSchedule: false,
      },
      passport: {
        Производитель: "Trane / TO VERIFY",
        Модель: "RTAF / RTAD family",
        "Серийный номер": "TO VERIFY",
        "Дата установки": "2020",
        Мощность: "TO VERIFY",
        "Сервисная организация": "UPGRADE / WinGroup demo",
        Регламент: "Ежемесячный обход, сезонное ТО",
      },
      recommendations: [
        "Проверить сервисное окно CH-1 перед ростом нагрузки.",
        "Сравнить COP с соседними чиллерами за 7 дней.",
      ],
    },
    {
      id: "fc-021",
      name: "Fan coil FC-021",
      displayName: "Фанкойл FC-021",
      sourceAlias: "BMS.FC.A.RETAIL.021",
      type: "fan_coil",
      systemId: "conditioning",
      floorId: "floor-12600",
      zoneId: "zone-retail-a",
      status: "warning",
      mode: "auto",
      updatedAt: "18 sec ago",
      position: { x: 27, y: 66 },
      model3d: {
        kind: "fan_coil",
        twinId: "fancoil-fc92",
        nodeId: "fan-coil-fc-021",
        position: { x: 27, y: 66, z: 0.4 },
        scale: 0.74,
      },
      telemetry: {
        "Supply temperature": "8.1 °C",
        "Return temperature": "13.6 °C",
        "Fan speed": "2 / Auto",
        "Valve position": "46%",
        Mode: "Auto",
        Setpoint: "22.0 °C",
        "Room temperature": "23.1 °C",
      },
      capabilities: {
        canRead: true,
        canWrite: false,
        hasAlarms: true,
        hasTrends: true,
        supportsAck: false,
        supportsSchedule: false,
      },
      passport: {
        Производитель: "TO VERIFY",
        Модель: "FC 92 / demo mapping",
        "Серийный номер": "INV-FC-0021",
        "Дата установки": "TO VERIFY",
        Мощность: "TO VERIFY",
        "Сервисная организация": "TO VERIFY",
        Регламент: "Фильтр, вентилятор, клапан, дренаж",
      },
      recommendations: [
        "Сверить открытие клапана с ростом температуры обратки.",
        "Проверить фильтр и балансировку ветки фанкойлов.",
      ],
    },
    {
      id: "ahu-vc13-03",
      name: "AHU VC-13-03",
      displayName: "Вентустановка VC-13-03",
      sourceAlias: "SCADA.VC13.03.STATUS",
      type: "ahu",
      systemId: "ventilation",
      floorId: "floor-12600",
      zoneId: "zone-service",
      status: "warning",
      mode: "manual",
      updatedAt: "24 sec ago",
      position: { x: 59, y: 67 },
      model3d: {
        kind: "ahu",
        twinId: "ahu-pv1",
        src: "/models/equipment/supply-vent-unit-01.glb",
        nodeId: "ventilation-vc13-03",
        position: { x: 59, y: 67, z: 0.8 },
        scale: 0.9,
      },
      telemetry: {
        "Supply air temp": "18.4 °C",
        "Return air temp": "23.0 °C",
        "Air flow": "TO VERIFY",
        "Filter status": "Warning",
        "Damper mode": "Manual",
      },
      capabilities: {
        canRead: true,
        canWrite: false,
        hasAlarms: true,
        hasTrends: true,
        supportsAck: false,
        supportsSchedule: false,
      },
      passport: {
        Производитель: "REMAK / TO VERIFY",
        Модель: "VC-13 group",
        "Серийный номер": "VENT-ASIA-PARK-TO-VERIFY",
        "Дата установки": "TO VERIFY",
        Мощность: "TO VERIFY",
        "Сервисная организация": "TO VERIFY",
        Регламент: "Фильтры, заслонки, локальный щит",
      },
      recommendations: [
        "Проверить локальный щит и ручной режим заслонки.",
        "Не выполнять удаленный reset до сверки BMS-тега.",
      ],
    },
    {
      id: "pump-shu2",
      name: "Pump group SHU-2",
      displayName: "Насосная группа ШУ-2",
      sourceAlias: "SCADA.CHW.PUMP.SHU2",
      type: "pump",
      systemId: "cooling",
      floorId: "floor-12600",
      zoneId: "zone-service",
      status: "critical",
      mode: "auto",
      updatedAt: "8 sec ago",
      position: { x: 74, y: 74 },
      telemetry: {
        Pressure: "6553.5 bar",
        Flow: "45.6 м3/ч",
        Vibration: "3.2 мм/с",
        "VFD frequency": "40 Hz",
      },
      capabilities: {
        canRead: true,
        canWrite: false,
        hasAlarms: true,
        hasTrends: true,
        supportsAck: false,
        supportsSchedule: false,
      },
      passport: {
        Производитель: "TO VERIFY",
        Модель: "Насосная группа холодоснабжения",
        "Серийный номер": "SHU-2-DEMO-6553",
        "Дата установки": "TO VERIFY",
        Мощность: "TO VERIFY",
        "Сервисная организация": "TO VERIFY",
        Регламент: "Проверка датчиков, VFD, вибрации",
      },
      recommendations: [
        "DP 6553.5 bar похож на ошибку scaling/register.",
        "До подтверждения данных не выполнять сброс аварии.",
      ],
    },
    {
      id: "sens-dp-01",
      name: "DP Sensor CHW-01",
      displayName: "Датчик DP CHW-01",
      sourceAlias: "SCADA.CHW.DP_01.PV",
      type: "sensor",
      systemId: "cooling",
      floorId: "floor-12600",
      zoneId: "zone-service",
      status: "critical",
      mode: "auto",
      updatedAt: "8 sec ago",
      position: { x: 83, y: 59 },
      telemetry: {
        Value: "6553.5 bar",
        Range: "0-10 bar / TO VERIFY",
        Quality: "suspect",
        Online: true,
      },
      capabilities: {
        canRead: true,
        canWrite: false,
        hasAlarms: true,
        hasTrends: true,
        supportsAck: false,
        supportsSchedule: false,
      },
      passport: {
        Производитель: "TO VERIFY",
        Модель: "Differential pressure transmitter",
        "Серийный номер": "SNS-DP-0001",
        "Дата установки": "TO VERIFY",
        Мощность: "N/A",
        "Сервисная организация": "TO VERIFY",
        Регламент: "Калибровка нуля, проверка импульсных линий",
      },
      recommendations: [
        "Сверить единицы измерения, historian tag и Modbus/BACnet register.",
        "Отметить точку как data-quality issue до проверки.",
      ],
    },
    {
      id: "ahu-vc13-01",
      name: "AHU VC-13-01",
      displayName: "Вентустановка VC-13-01",
      sourceAlias: "SCADA.VC13.01.STATUS",
      type: "ahu",
      systemId: "ventilation",
      floorId: "floor-13500",
      zoneId: "zone-ahu",
      status: "normal",
      mode: "auto",
      updatedAt: "21 sec ago",
      position: { x: 71, y: 26 },
      model3d: {
        kind: "ahu",
        twinId: "ahu-pv1",
        src: "/models/equipment/supply-vent-unit-01.glb",
        nodeId: "ventilation-vc13-01",
        position: { x: 71, y: 26, z: 0.8 },
        scale: 0.9,
      },
      telemetry: {
        "Supply air temp": "17.9 °C",
        CO2: "612 ppm",
        "Air flow": "RUN / TO VERIFY",
        "Filter status": "Normal",
      },
      capabilities: {
        canRead: true,
        canWrite: false,
        hasAlarms: false,
        hasTrends: true,
        supportsAck: false,
        supportsSchedule: false,
      },
      passport: {
        Производитель: "REMAK / TO VERIFY",
        Модель: "VC-13 group",
        "Серийный номер": "VENT-VC13-01",
        "Дата установки": "TO VERIFY",
        Мощность: "TO VERIFY",
        "Сервисная организация": "TO VERIFY",
        Регламент: "Фильтры, вентилятор, заслонки",
      },
      recommendations: ["Сохранить режим Auto, отклонений по расходу не выявлено."],
    },
    {
      id: "ct-001",
      name: "Cooling tower CT-1",
      displayName: "Градирня CT-1",
      sourceAlias: "SCADA.CHW.CT1.STATUS",
      type: "pump",
      systemId: "cooling",
      floorId: "floor-13500",
      zoneId: "zone-roof",
      status: "normal",
      mode: "auto",
      updatedAt: "31 sec ago",
      position: { x: 27, y: 27 },
      telemetry: {
        "Fan status": "RUN",
        "Water temp": "22.4 °C",
        Level: "Normal",
        Conductivity: "TO VERIFY",
      },
      capabilities: {
        canRead: true,
        canWrite: false,
        hasAlarms: false,
        hasTrends: true,
        supportsAck: false,
        supportsSchedule: false,
      },
      passport: {
        Производитель: "TO VERIFY",
        Модель: "Cooling tower small",
        "Серийный номер": "INV-CT-0001",
        "Дата установки": "TO VERIFY",
        Мощность: "TO VERIFY",
        "Сервисная организация": "TO VERIFY",
        Регламент: "Вентилятор, форсунки, поддон, уровень",
      },
      recommendations: ["Проверить вентилятор и поддон при следующем обходе."],
    },
  ],
  alarms: [
    {
      id: "alm-dp-6553",
      equipmentId: "pump-shu2",
      severity: "critical",
      status: "active",
      timestamp: "01:42",
      title: "DP 6553.x bar на ШУ-2",
      message: "Физически невозможное значение перепада давления, нужна проверка scaling/register.",
    },
    {
      id: "alm-dp-sensor",
      equipmentId: "sens-dp-01",
      severity: "critical",
      status: "active",
      timestamp: "01:42",
      title: "DP Sensor CHW-01: suspect quality",
      message: "Точка online, но значение выходит за ожидаемый диапазон.",
    },
    {
      id: "alm-return-temp",
      equipmentId: "fc-021",
      severity: "warning",
      status: "active",
      timestamp: "01:18",
      title: "Рост температуры обратки фанкойлов",
      message: "Контур торговой зоны показывает повышенную обратку при открытии клапана 46%.",
    },
    {
      id: "alm-ahu-manual",
      equipmentId: "ahu-vc13-03",
      severity: "warning",
      status: "active",
      timestamp: "01:05",
      title: "VC-13-03: заслонка в ручном режиме",
      message: "Нужно сверить локальный щит и команду диспетчера.",
    },
    {
      id: "alm-chiller-service",
      equipmentId: "ch-001",
      severity: "warning",
      status: "active",
      timestamp: "00:49",
      title: "CH-1 ожидает сервисное окно",
      message: "Плановое обслуживание чиллера готово к заявке.",
    },
  ],
  events: [
    {
      id: "evt-opened",
      type: "event",
      timestamp: "01:56",
      title: "Workspace открыт",
      description: "Объектный контекст восстановлен из mock registry.",
    },
    {
      id: "evt-vc13-manual",
      equipmentId: "ahu-vc13-03",
      type: "event",
      timestamp: "01:05",
      title: "AHU VC-13-03 перешла в ручной режим",
      description: "Событие получено из demo BMS context.",
    },
    {
      id: "evt-chiller-maint",
      equipmentId: "ch-001",
      type: "maintenance",
      timestamp: "00:49",
      title: "CH-1 добавлен в сервисный список",
      description: "Создание внешней заявки будет подключено в следующем релизе.",
    },
    {
      id: "evt-command-local",
      equipmentId: "fc-021",
      type: "command",
      timestamp: "00:37",
      title: "Mock command prepared",
      description: "Команда сформирована локально; API интеграция не подключена.",
    },
  ],
  commands: [
    { id: "mode-auto", equipmentType: "all", label: "Mode", value: "Auto", requiresConfirmation: true },
    { id: "mode-service", equipmentType: "all", label: "Mode", value: "Service", requiresConfirmation: true },
    { id: "target-temp", equipmentType: "fan_coil", label: "Target temperature", value: "22 °C", requiresConfirmation: true },
    { id: "fan-speed", equipmentType: "fan_coil", label: "Fan speed", value: "Auto", requiresConfirmation: true },
    { id: "enable-disable", equipmentType: "all", label: "Enable / disable", value: "Prepare", requiresConfirmation: true },
    { id: "reset-alarm", equipmentType: "all", label: "Reset alarm", value: "Prepare", requiresConfirmation: true },
  ],
  recommendedActions: [
    {
      id: "act-dp-verify-scaling",
      equipmentId: "pump-shu2",
      alarmId: "alm-dp-6553",
      title: "Mark DP anomaly as data-quality issue",
      description: "Freeze remote reset, verify sensor range, register scaling and historian mapping before any control action.",
      commandId: "mode-service",
      commandLabel: "Prepare local service mode note",
      risk: "low",
      expectedOutcome: "Operator sees the alarm linked to a safe verification workflow instead of a reset attempt.",
    },
    {
      id: "act-dp-sensor-calibration",
      equipmentId: "sens-dp-01",
      alarmId: "alm-dp-sensor",
      title: "Create sensor calibration check",
      description: "Prepare a local command log that requests zero calibration and impulse line inspection for DP Sensor CHW-01.",
      commandId: "enable-disable",
      commandLabel: "Prepare calibration check",
      risk: "low",
      expectedOutcome: "The sensor alarm is converted into a traceable service action in the journal.",
    },
    {
      id: "act-fc-raise-setpoint",
      equipmentId: "fc-021",
      alarmId: "alm-return-temp",
      title: "Prepare setpoint review for FC-021",
      description: "Do not write to BMS; prepare a local target temperature review and fan speed check for the operator.",
      commandId: "target-temp",
      commandLabel: "Prepare target temperature review",
      risk: "medium",
      expectedOutcome: "Fan coil investigation is recorded without sending a live command.",
    },
    {
      id: "act-ahu-manual-review",
      equipmentId: "ahu-vc13-03",
      alarmId: "alm-ahu-manual",
      title: "Prepare manual damper inspection",
      description: "Request local panel verification and keep remote reset disabled until the manual mode source is confirmed.",
      commandId: "mode-service",
      commandLabel: "Prepare service inspection",
      risk: "medium",
      expectedOutcome: "Manual-mode alarm becomes a clear field inspection workflow.",
    },
    {
      id: "act-chiller-service-window",
      equipmentId: "ch-001",
      alarmId: "alm-chiller-service",
      title: "Prepare CH-1 service window",
      description: "Record a local service-window command preparation for the chiller without external work-order integration.",
      commandId: "mode-service",
      commandLabel: "Prepare service window",
      risk: "low",
      expectedOutcome: "Chiller maintenance intent appears in the command journal.",
    },
  ],
};
