export type WeddingHairstyleApprovedAssetMapping = {
  slug: string;
  assetFilename: string;
  variant?: "closeup";
  isApproved: true;
};

export const weddingHairstylesTop100ApprovedAssetMappings = [
  { slug: "smooth-low-bun-wedding-hairstyle", assetFilename: "smooth-low-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "classic-low-bun-wedding-hairstyle", assetFilename: "classic-chignon-wedding-hairstyle.png", isApproved: true },
  { slug: "sleek-low-bun-wedding-hairstyle", assetFilename: "sculptural-sleek-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "center-part-low-bun-wedding-hairstyle", assetFilename: "low-bun-with-tendrils-wedding-hairstyle.png", isApproved: true },
  { slug: "romantic-low-bun-wedding-hairstyle", assetFilename: "side-bun-wedding-hairstyle.png", isApproved: true },
  {
    slug: "pearl-low-bun-wedding-hairstyle",
    assetFilename: "shell-bun-wedding-hairstyle-closeup.png",
    variant: "closeup",
    isApproved: true,
  },
  { slug: "twisted-low-bun-wedding-hairstyle", assetFilename: "twisted-low-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "braided-low-bun-wedding-hairstyle", assetFilename: "braided-low-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "chignon-low-bun-wedding-hairstyle", assetFilename: "gibson-tuck-wedding-hairstyle.png", isApproved: true },
  { slug: "soft-volume-low-bun-wedding-hairstyle", assetFilename: "wrapped-low-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "elegant-high-bun-wedding-hairstyle", assetFilename: "regal-high-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "modern-high-bun-wedding-hairstyle", assetFilename: "bouffant-bridal-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "ballerina-bun-wedding-hairstyle", assetFilename: "shell-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "textured-high-bun-wedding-hairstyle", assetFilename: "low-textured-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "veil-ready-high-bun-wedding-hairstyle", assetFilename: "tiara-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "curly-high-bun-wedding-hairstyle", assetFilename: "high-soft-chignon-wedding-hairstyle.png", isApproved: true },
  { slug: "braided-high-bun-wedding-hairstyle", assetFilename: "braided-chignon-wedding-hairstyle.png", isApproved: true },
  {
    slug: "sculpted-high-bun-wedding-hairstyle",
    assetFilename: "sculptural-sleek-bun-wedding-hairstyle-closeup.png",
    variant: "closeup",
    isApproved: true,
  },
  { slug: "messy-high-bun-wedding-hairstyle", assetFilename: "rosette-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "knotted-high-bun-wedding-hairstyle", assetFilename: "knotted-low-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "textured-updo-wedding-hairstyle", assetFilename: "voluminous-textured-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "soft-updo-wedding-hairstyle", assetFilename: "asymmetrical-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "romantic-updo-wedding-hairstyle", assetFilename: "romantic-messy-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "floral-updo-wedding-hairstyle", assetFilename: "floral-inspired-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "loose-updo-wedding-hairstyle", assetFilename: "face-framing-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "french-twist-updo-wedding-hairstyle", assetFilename: "french-twist-wedding-hairstyle.png", isApproved: true },
  { slug: "modern-twist-updo-wedding-hairstyle", assetFilename: "italian-twist-wedding-hairstyle.png", isApproved: true },
  { slug: "crown-updo-wedding-hairstyle", assetFilename: "spiral-pinned-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "vintage-updo-wedding-hairstyle", assetFilename: "pleated-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "airy-updo-wedding-hairstyle", assetFilename: "grecian-tucked-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "hollywood-waves-wedding-hairstyle", assetFilename: "hollywood-waves-wedding-hairstyle.png", isApproved: true },
  { slug: "boho-beach-waves-wedding-hairstyle", assetFilename: "boho-beach-waves-wedding-hairstyle.png", isApproved: true },
  { slug: "glossy-soft-waves-wedding-hairstyle", assetFilename: "soft-glam-waves-wedding-hairstyle.png", isApproved: true },
  { slug: "side-swept-waves-wedding-hairstyle", assetFilename: "side-swept-waves-wedding-hairstyle.png", isApproved: true },
  { slug: "old-hollywood-waves-wedding-hairstyle", assetFilename: "old-hollywood-waves-wedding-hairstyle.png", isApproved: true },
  { slug: "mermaid-waves-wedding-hairstyle", assetFilename: "mermaid-waves-wedding-hairstyle.png", isApproved: true },
  { slug: "brushed-out-waves-wedding-hairstyle", assetFilename: "brushed-out-glam-curls-wedding-hairstyle.png", isApproved: true },
  { slug: "vintage-waves-wedding-hairstyle", assetFilename: "s-waves-wedding-hairstyle.png", isApproved: true },
  { slug: "loose-glam-waves-wedding-hairstyle", assetFilename: "vintage-glam-curls-wedding-hairstyle.png", isApproved: true },
  { slug: "waterfall-waves-wedding-hairstyle", assetFilename: "waterfall-curls-wedding-hairstyle.png", isApproved: true },
  { slug: "half-up-half-down-curls-wedding-hairstyle", assetFilename: "half-up-curls-wedding-hairstyle.png", isApproved: true },
  { slug: "half-up-soft-waves-wedding-hairstyle", assetFilename: "half-up-middle-part-soft-waves-wedding-hairstyle.png", isApproved: true },
  { slug: "half-up-braid-crown-wedding-hairstyle", assetFilename: "half-up-braid-wedding-hairstyle.png", isApproved: true },
  { slug: "half-up-twists-wedding-hairstyle", assetFilename: "half-up-side-twists-wedding-hairstyle.png", isApproved: true },
  { slug: "half-up-pearl-pins-wedding-hairstyle", assetFilename: "half-up-sleek-crown-wedding-hairstyle.png", isApproved: true },
  { slug: "half-up-bow-detail-wedding-hairstyle", assetFilename: "half-up-twisted-crown-wedding-hairstyle.png", isApproved: true },
  { slug: "half-up-ponytail-wedding-hairstyle", assetFilename: "half-up-side-swept-front-wedding-hairstyle.png", isApproved: true },
  { slug: "half-up-floral-detail-wedding-hairstyle", assetFilename: "half-up-rosette-wedding-hairstyle.png", isApproved: true },
  { slug: "half-up-volume-curls-wedding-hairstyle", assetFilename: "half-up-pinned-curls-wedding-hairstyle.png", isApproved: true },
  { slug: "half-up-veil-ready-wedding-hairstyle", assetFilename: "half-up-volume-crown-wedding-hairstyle.png", isApproved: true },
  { slug: "boho-braid-wedding-hairstyle", assetFilename: "half-up-fishtail-accent-wedding-hairstyle.png", isApproved: true },
  { slug: "fishtail-braid-wedding-hairstyle", assetFilename: "side-fishtail-braid-wedding-hairstyle.png", isApproved: true },
  { slug: "crown-braid-wedding-hairstyle", assetFilename: "crown-braid-wedding-hairstyle.png", isApproved: true },
  { slug: "dutch-braid-wedding-hairstyle", assetFilename: "braided-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "halo-braid-wedding-hairstyle", assetFilename: "crown-twist-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "waterfall-braid-wedding-hairstyle", assetFilename: "half-up-waterfall-braid-wedding-hairstyle.png", isApproved: true },
  { slug: "side-braid-wedding-hairstyle", assetFilename: "side-braid-with-curls-wedding-hairstyle.png", isApproved: true },
  { slug: "braided-ponytail-wedding-hairstyle", assetFilename: "braided-ponytail-wedding-hairstyle.png", isApproved: true },
  { slug: "rope-braid-wedding-hairstyle", assetFilename: "braided-side-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "pull-through-braid-wedding-hairstyle", assetFilename: "pull-through-braid-wedding-hairstyle.png", isApproved: true },
  { slug: "sleek-low-ponytail-wedding-hairstyle", assetFilename: "smooth-low-ponytail-wedding-hairstyle.png", isApproved: true },
  { slug: "soft-curled-ponytail-wedding-hairstyle", assetFilename: "low-curled-ponytail-wedding-hairstyle.png", isApproved: true },
  { slug: "bubble-ponytail-wedding-hairstyle", assetFilename: "bubble-ponytail-wedding-hairstyle.png", isApproved: true },
  { slug: "wrapped-ponytail-wedding-hairstyle", assetFilename: "twisted-low-ponytail-wedding-hairstyle.png", isApproved: true },
  { slug: "glam-high-ponytail-wedding-hairstyle", assetFilename: "voluminous-high-ponytail-wedding-hairstyle.png", isApproved: true },
  { slug: "romantic-ponytail-wedding-hairstyle", assetFilename: "side-ponytail-with-curls-wedding-hairstyle.png", isApproved: true },
  { slug: "side-part-ponytail-wedding-hairstyle", assetFilename: "deep-side-part-sleek-straight-hair-wedding-hairstyle.png", isApproved: true },
  { slug: "textured-low-ponytail-wedding-hairstyle", assetFilename: "textured-ponytail-wedding-hairstyle.png", isApproved: true },
  { slug: "braided-high-ponytail-wedding-hairstyle", assetFilename: "french-braid-low-pony-wedding-hairstyle.png", isApproved: true },
  { slug: "ribbon-detail-ponytail-wedding-hairstyle", assetFilename: "party-ponytail-wedding-hairstyle.png", isApproved: true },
  { slug: "pixie-texture-wedding-hairstyle", assetFilename: "soft-straight-blowout-curled-ends-wedding-hairstyle.png", isApproved: true },
  { slug: "short-wave-bob-wedding-hairstyle", assetFilename: "bouncy-blowout-wedding-hairstyle.png", isApproved: true },
  { slug: "sleek-bridal-bob-wedding-hairstyle", assetFilename: "center-part-sleek-straight-hair-wedding-hairstyle.png", isApproved: true },
  { slug: "side-part-short-curls-wedding-hairstyle", assetFilename: "curls-with-side-part-wedding-hairstyle.png", isApproved: true },
  { slug: "finger-waves-bob-wedding-hairstyle", assetFilename: "finger-waves-bridal-wedding-hairstyle.png", isApproved: true },
  { slug: "tucked-back-short-style-wedding-hairstyle", assetFilename: "pinned-back-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "pearl-pin-bob-wedding-hairstyle", assetFilename: "headband-wedding-hairstyle.png", isApproved: true },
  { slug: "soft-volume-lob-wedding-hairstyle", assetFilename: "long-textured-blowout-wedding-hairstyle.png", isApproved: true },
  { slug: "side-swept-bob-wedding-hairstyle", assetFilename: "side-swept-curls-wedding-hairstyle.png", isApproved: true },
  { slug: "vintage-short-glam-wedding-hairstyle", assetFilename: "barrel-curls-wedding-hairstyle.png", isApproved: true },
  { slug: "half-up-locs-bridal-wedding-hairstyle", assetFilename: "half-up-locs-bridal-wedding-hairstyle.png", isApproved: true },
  { slug: "locs-bun-bridal-wedding-hairstyle", assetFilename: "high-loc-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "locs-crown-bridal-wedding-hairstyle", assetFilename: "low-loc-bun-wedding-hairstyle.png", isApproved: true },
  { slug: "locs-ponytail-bridal-wedding-hairstyle", assetFilename: "defined-natural-curls-down-wedding-hairstyle.png", isApproved: true },
  { slug: "braided-locs-updo-wedding-hairstyle", assetFilename: "rolled-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "floral-locs-style-wedding-hairstyle", assetFilename: "romantic-updo-with-accessories-wedding-hairstyle.png", isApproved: true },
  { slug: "twisted-locs-bun-wedding-hairstyle", assetFilename: "twist-out-bridal-style-wedding-hairstyle.png", isApproved: true },
  { slug: "soft-curls-locs-wedding-hairstyle", assetFilename: "soft-loose-curls-wedding-hairstyle.png", isApproved: true },
  { slug: "locs-half-updo-wedding-hairstyle", assetFilename: "half-up-waves-wedding-hairstyle.png", isApproved: true },
  { slug: "locs-side-swept-wedding-hairstyle", assetFilename: "defined-spiral-curls-wedding-hairstyle.png", isApproved: true },
  { slug: "fulani-braids-bridal-wedding-hairstyle", assetFilename: "fulani-braid-bridal-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "goddess-braids-bridal-wedding-hairstyle", assetFilename: "double-braid-bridal-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "knotless-braids-bun-wedding-hairstyle", assetFilename: "messy-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "cornrow-low-bun-wedding-hairstyle", assetFilename: "tucked-nape-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "twist-crown-bridal-wedding-hairstyle", assetFilename: "flat-twist-bridal-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "passion-twists-updo-wedding-hairstyle", assetFilename: "textured-side-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "marley-twists-bun-wedding-hairstyle", assetFilename: "defined-afro-curls-bridal-wedding-hairstyle.png", isApproved: true },
  { slug: "natural-curly-puff-wedding-hairstyle", assetFilename: "afro-puff-bridal-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "defined-coils-updo-wedding-hairstyle", assetFilename: "natural-coily-bridal-updo-wedding-hairstyle.png", isApproved: true },
  { slug: "afro-textured-side-part-wedding-hairstyle", assetFilename: "regal-afro-wedding-hairstyle.png", isApproved: true },
] satisfies readonly WeddingHairstyleApprovedAssetMapping[];
