import type {
  EquipmentTwinConfig,
  EquipmentTwinId,
  EquipmentTwinSystem,
} from "../../lib/dispatch/equipmentTwinTypes";

export const equipmentTwinSystemLabels: Record<EquipmentTwinSystem, string> = {
  ventilation: "Вентиляция",
  cooling: "Холодоснабжение",
  conditioning: "Кондиционирование",
};

export const equipmentTwins: EquipmentTwinConfig[] = [
  {
    id: "ahu-pv1",
    title: "Приточная вентустановка ПВ-1",
    shortTitle: "ПВ-1",
    system: "ventilation",
    status: "В работе",
    modelPath: "/models/equipment/supply-vent-unit-01-assembled.glb",
    location: "Asia Park Astana / Венткамера / +11.400",
    manufacturer: "TO VERIFY",
    model: "Приточная вентиляционная установка / TO VERIFY",
    serialNumber: "TO VERIFY",
    inventoryNumber: "INV-VENT-0001",
    year: "TO VERIFY",
    lastEvent: "Без активных аварий",
    serviceNote: "Плановый обход: замечаний нет, режим read-only",
    trends: [
      "Температура приточного воздуха",
      "Температура обратки",
      "Давление",
      "Расход воздуха",
      "Состояние фильтра",
    ],
    relatedSystems: ["Вентиляция", "Фанкойлы", "BMS/SCADA"],
    explodedTransforms: {
      damperGroup: { position: [-1.8, 0, 0] },
      filterGroup: { position: [-0.95, 0.05, 0.35] },
      coilGroup: { position: [-0.2, 0.08, 0.42] },
      fanGroup: { position: [0.75, 0.12, 0.38] },
      removablePanelsGroup: { position: [0, 0.78, 0.62] },
      fastenersGroup: { position: [1.1, -0.28, 0.52] },
    },
  },
  {
    id: "chiller",
    title: "Чиллер CH-1",
    shortTitle: "Чиллер",
    system: "cooling",
    status: "В работе",
    modelPath: "/models/dispatch/chiller.glb",
    location: "Asia Park Astana / Холодоснабжение / Машинная зона",
    manufacturer: "Trane / TO VERIFY",
    model: "Chiller / TO VERIFY",
    serialNumber: "TO VERIFY",
    inventoryNumber: "INV-CH-0001",
    year: "TO VERIFY",
    lastEvent: "Плановое обслуживание чиллера CH-1",
    serviceNote: "Проверить контур, компрессор, теплообменник и температурные тренды",
    trends: ["Температура воды", "Давление", "Энергия", "Статус компрессора"],
    relatedSystems: ["Холодоснабжение", "Насосные группы", "BMS/SCADA"],
    explodedTransforms: {
      chillerShellGroup: { position: [0, 0, 0] },
      compressorGroup: { position: [0.85, -0.12, 0.35] },
      heatExchangerGroup: { position: [-0.85, 0.02, 0.38] },
      fanGroup: { position: [0.2, 0.72, 0.2] },
      pipeGroup: { position: [0.35, 0, -0.46] },
      removablePanelsGroup: { position: [0, 0.42, 0.72] },
      fastenersGroup: { position: [1.12, 0.12, 0.62] },
    },
  },
  {
    id: "cooling-tower-small",
    title: "Градирня CT-1",
    shortTitle: "Градирня",
    system: "cooling",
    status: "В работе",
    modelPath: "/models/dispatch/cooling-tower-small.glb",
    location: "Asia Park Astana / Кровля / Холодоснабжение",
    manufacturer: "TO VERIFY",
    model: "Cooling tower small / TO VERIFY",
    serialNumber: "TO VERIFY",
    inventoryNumber: "INV-CT-0001",
    year: "TO VERIFY",
    lastEvent: "Контроль вентилятора градирни",
    serviceNote: "Проверить вентилятор, форсунки, поддон, уровень воды и загрязнение теплообмена",
    trends: ["Температура воды", "Статус вентилятора", "Расход", "Авария уровня"],
    relatedSystems: ["Холодоснабжение", "Чиллеры", "BMS/SCADA"],
    explodedTransforms: {
      towerShellGroup: { position: [0, 0, 0] },
      fanGroup: { position: [0, 0.95, 0] },
      fillPackGroup: { position: [-0.78, 0.08, 0.22] },
      basinGroup: { position: [0, 0, 0] },
      sprayPipeGroup: { position: [0.62, 0.38, 0.24] },
      removablePanelsGroup: { position: [0, 0.72, 0.32] },
    },
  },
  {
    id: "fancoil-fc92",
    title: "Фанкойл FC-92",
    shortTitle: "Фанкойл",
    system: "conditioning",
    status: "В работе",
    modelPath: "/models/dispatch/fancoil-fc92.glb",
    location: "Asia Park Astana / Коммерческая зона / Кондиционирование",
    manufacturer: "TO VERIFY",
    model: "Fancoil FC 92 I01 / TO VERIFY",
    serialNumber: "TO VERIFY",
    inventoryNumber: "INV-FC-0092",
    year: "TO VERIFY",
    lastEvent: "Без активных аварий",
    serviceNote: "Проверить фильтр, вентилятор, клапан, дренаж и теплообменник",
    trends: ["Температура зоны", "Скорость вентилятора", "Клапан", "Состояние фильтра"],
    relatedSystems: ["Кондиционирование", "Фанкойлы", "BMS/SCADA"],
    explodedTransforms: {
      fancoilShellGroup: { position: [0, 0, 0] },
      frontPanelGroup: { position: [0, 0, 0.68] },
      filterGroup: { position: [-0.72, -0.02, 0.52] },
      fanGroup: { position: [0.34, 0.02, 0.56] },
      coilGroup: { position: [-0.18, 0.12, 0.72] },
      drainTrayGroup: { position: [0, -0.38, 0.5] },
      pipeGroup: { position: [0.78, 0.02, 0.35] },
    },
  },
  {
    id: "multi-split-system",
    title: "Мультисплит система MS-1",
    shortTitle: "Мультисплит",
    system: "conditioning",
    status: "TO VERIFY",
    modelPath: "/models/dispatch/multi-split-system.glb",
    location: "Asia Park Astana / Кондиционирование / TO VERIFY",
    manufacturer: "TO VERIFY",
    model: "Multi split system / TO VERIFY",
    serialNumber: "TO VERIFY",
    inventoryNumber: "INV-MS-0001",
    year: "TO VERIFY",
    lastEvent: "Оборудование добавлено в demo registry",
    serviceNote: "Проверить наружный блок, внутренние блоки, трассы, дренаж и режимы работы",
    trends: ["Температура зоны", "Режим", "Компрессор", "Потребление"],
    relatedSystems: ["Кондиционирование", "BMS/SCADA", "Заявки"],
    explodedTransforms: {
      multiSplitOutdoorUnitGroup: { position: [0, 0, 0] },
      multiSplitIndoorUnitsGroup: { position: [0, 0, 0] },
      compressorGroup: { position: [0.68, -0.1, 0.38] },
      fanGroup: { position: [-0.62, 0.06, 0.46] },
      coilGroup: { position: [0.18, 0.2, 0.64] },
      pipeRoutesGroup: { position: [0, 0, 0.18] },
      removablePanelsGroup: { position: [0.22, 0.56, 0.64] },
    },
  },
];

export const equipmentTwinIds = equipmentTwins.map((item) => item.id);

export const equipmentTwinSectionMap: Partial<Record<string, EquipmentTwinId[]>> = {
  cooling: ["chiller", "cooling-tower-small"],
  fanCoils: ["fancoil-fc92", "multi-split-system"],
  ventilation: ["ahu-pv1"],
  equipment: ["ahu-pv1", "chiller", "cooling-tower-small", "fancoil-fc92", "multi-split-system"],
  tickets: ["chiller", "multi-split-system"],
  trends: ["chiller", "fancoil-fc92", "multi-split-system"],
  ai: ["chiller", "cooling-tower-small", "fancoil-fc92", "multi-split-system"],
};

export const equipmentTwinNodeMap: Record<EquipmentTwinId, string> = {
  "ahu-pv1": "ventilation-vc13",
  chiller: "chiller-ch1",
  "cooling-tower-small": "cooling-circuits",
  "fancoil-fc92": "fan-coils",
  "multi-split-system": "fan-coils",
};

export const equipmentTwinSectionIdMap: Record<EquipmentTwinId, string> = {
  "ahu-pv1": "ventilation",
  chiller: "cooling",
  "cooling-tower-small": "cooling",
  "fancoil-fc92": "fanCoils",
  "multi-split-system": "fanCoils",
};

export function getEquipmentTwinById(id: EquipmentTwinId) {
  return equipmentTwins.find((item) => item.id === id) ?? equipmentTwins[0];
}
